services:
  mysql:
    image: mysql:8.0
    container_name: lectureDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root          # 루트 계정 비밀번호
      MYSQL_DATABASE: concert                  # 생성할 DB 이름
      TZ: Asia/Seoul                        # 시간대 설정
    ports:
      - "3309:3306"

