services:
  mysql:
    image: mysql:latest
    container_name: concert_db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: concert
  redis:
    image: redis:7.2
    container_name: concert_redis
    ports:
      - "6379:6379"
    restart: always